steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime"
      - "-f"
      - "apps/runtime/Dockerfile"
      - "."
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime"
substitutions:
  _REGION: "europe-west1"
