steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime:${_IMAGE_TAG}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime:latest"
      - "-f"
      - "apps/runtime/Dockerfile"
      - "."
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime:${_IMAGE_TAG}"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/cadris/runtime:latest"
substitutions:
  _REGION: "europe-west1"
  _IMAGE_TAG: "latest"
